name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # v1.0.0 のようなタグがプッシュされた時のみ実行

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write # PyPIのTrusted Publishingに必要

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install pypa/build
      run: python -m pip install build --user

    - name: Build a binary wheel and a source tarball
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      # PyPIのTrusted Publishingを設定している場合、APIトークンの設定は不要です
